project/directory/urls.py
from django.conf.urls import patterns, url
from project.directory.views import (
    HomePageView, SubmitEntryView, EntryDetailView,
    TagEntriesListView, SearchResultsView
)

urlpatterns = patterns('',

    url(r'^$', HomePageView.as_view(), name="home"),
    url(r'^submit/$', SubmitEntryView.as_view(), name="submit"),
    url(r'^entries/(?P<slug>[\w-]+)/$', EntryDetailView.as_view(), name='detail'),
    url(r'^tags/(?P<slug>[\w-]+)/$', TagEntriesListView.as_view(), name='tag-entries'),
    url(r'^search/results/$', SearchResultsView.as_view(), name='search-results')
)

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from project.common.views import RobotsView

api_urls = [
    url(r'^directory/', view=include('project.directory.urls_api', namespace='directory')),
]

urlpatterns = [

    url('api/', include(api_urls, namespace='api')),

    url(r'^', view=include('project.directory.urls', namespace='directory')),
    url(r'^accounts/', view=include('project.accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),

    # Robots
    url(regex=r'^robots.txt$', view=RobotsView.as_view()),
]

urlpatterns += staticfiles_urlpatterns()

project/directory/models.py
import uuid
from cloudinary.models import CloudinaryField
from django.db import models
from django.utils.text import slugify
from django_dbq.models import Job
from project.accounts.models import User


class Tag(models.Model):

    class Meta:
        verbose_name_plural = "Tags"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    modified = models.DateTimeField(auto_now=True)

    name = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Entry(models.Model):

    class Meta:
        ordering = ['-created']
        verbose_name_plural = "Entries"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    modified = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True)
    short_description = models.CharField(max_length=255)
    author = models.ForeignKey(User, related_name="entries")
    tags = models.ManyToManyField(Tag, related_name="tags", blank=True)

    cover = CloudinaryField(null=True, blank=True)
    website_url = models.URLField(null=True, blank=True)
    repo_url = models.URLField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    is_approved = models.BooleanField(default=False)
    is_featured = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def _get_cover_link(self, url):
        if not url:
            return None

        return u'<img width="80px" src="%s" />' % (url.url)

    def thumbnail_cover(self):
        return self._get_cover_link(self.cover)
    thumbnail_cover.short_description = 'Cover Thumbnail'
    thumbnail_cover.allow_tags = True

    def send_user_approval_email(self):
        """ Notify the user that the submission got approved """
        workspace = {
            "subject": "Your submission to Built with Electron got approved.",
            "recipient_list": [self.author.email],
            "mail_params": {
                'username': self.author.username,
                'entry_name': self.name,
                'entry_slug': self.slug
            },
            "plain_template": "emails/submission_approval.txt",
            "html_template": "emails/submission_approval.html"
        }

        Job.objects.create(name='send_email', workspace=workspace)

    def send_admins_new_entry_email(self):
        """ Notify admins that a new submission awaits approval """
        admins = User.objects.filter(is_active=True, is_admin=True)
        admins_emails = [user.email for user in admins]

        workspace = {
            "subject": "There is a new submission at Built with Electron.",
            "recipient_list": admins_emails,
            "mail_params": {
                'entry_name': self.name
            },
            "plain_template": "emails/admin_new_submission.txt",
            "html_template": "emails/admin_new_submission.html"
        }

        Job.objects.create(name='send_email', workspace=workspace)

    def save(self, *args, **kwargs):
        """ If `is_approved` changed and is True, email the user """
        try:
            prev_state = Entry.objects.get(id=self.id).is_approved
            new_state = self.is_approved

            if (prev_state != new_state) and new_state:
                self.send_user_approval_email()

        except self.DoesNotExist:
            pass

        # Auto-populate the slugfield
        if not self.slug:
            self.slug = slugify(self.name)

        super(Entry, self).save(*args, **kwargs)

project/directory/forms.py
from django import forms


class SearchForm(forms.Form):
    keywords = forms.CharField(label='Keywords', max_length=100)

project/directory/views.py
from django.core import serializers
from django.conf import settings
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormMixin
from project.accounts.helpers import get_oauth_url
from project.directory.models import Entry, Tag
from project.directory.forms import SearchForm


class HomePageView(ListView):

    model = Entry
    template_name = "home.html"
    paginate_by = 6

    def get_queryset(self):
        latest = Entry.objects.filter(is_approved=True, is_featured=False).order_by('-created')
        return latest

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['is_homepage'] = True
        context['OAUTH_URL'] = get_oauth_url()
        return context


class SubmitEntryView(TemplateView):

    template_name = "directory/submit.html"

    def get_context_data(self, **kwargs):
        tags = Tag.objects.all()
        tags_json = serializers.serialize('json', tags)

        context = super(SubmitEntryView, self).get_context_data(**kwargs)
        context['OAUTH_URL'] = get_oauth_url()
        context['tags'] = tags_json
        return context


class EntryDetailView(FormMixin, DetailView):

    model = Entry
    slug_field = 'slug'
    template_name = "directory/detail.html"

    def get_context_data(self, **kwargs):
        context = super(EntryDetailView, self).get_context_data(**kwargs)
        context['SITE_URL'] = settings.SITE_URL
        return context


class TagEntriesListView(ListView):

    model = Entry
    template_name = "directory/tag-entries.html"
    paginate_by = 10

    def get_queryset(self):
        slug = self.kwargs['slug']
        tag = get_object_or_404(Tag, name=slug)
        queryset = Entry.objects.filter(tags=tag, is_approved=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(TagEntriesListView, self).get_context_data(**kwargs)
        context['tag_name'] = self.kwargs['slug']
        return context


class SearchResultsView(FormMixin, ListView):

    model = Entry
    template_name = "directory/search-results.html"
    form_class = SearchForm

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        context = self.get_context_data(object_list=self.object_list)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        self.queryset = self.get_queryset()
        return super(SearchResultsView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        keywords = self.request.POST.get('keywords')
        if keywords:
            return Entry.objects.filter(
                Q(name__icontains=keywords) | Q(short_description__icontains=keywords) |
                Q(author__username__icontains=keywords) | Q(description__icontains=keywords)
            ).exclude(is_approved=False)
        return []

    def get_context_data(self, **kwargs):
        context = super(SearchResultsView, self).get_context_data(**kwargs)

        object_list = context['object_list']

        if object_list:
            context['found'] = True
        else:
            context['found'] = False
            context['object_list'] = Entry.objects.filter(is_approved=True)

        context['keywords'] = self.request.POST.get('keywords')
        return context

templates/directory/detail.html
{% extends "base.html" %}
{% block body_class %}detail-page{% endblock %}
{% block title %}{{ object.name }} - {% endblock %}
{% block pagetitle %}{{ object.name }}: {{object.short_description}}{% endblock %}

{% block content %}

<div class="container">

  {% if object.cover %}
  <img src="{{ object.cover.url }}" alt="{{ object.name }}" title="{{ object.name }}" class="img-responsive cover" />
  {% endif %}

  <h1>
    {{ object.name }}
    <span class="links">
      <a href="{{ object.website_url }}" target="_blank"><i class="fa fa-link"></i></a>
      {% if object.repo_url %}<a href="{{ object.repo_url }}" target="_blank"><i class="fa fa-github"></i></a>{% endif %}
      <a class="btn btn-info btn-twitter" href="https://twitter.com/intent/tweet?url={{ SITE_URL }}{% url 'directory:detail' object.slug %}&text={{ object.name }}: {{ object.short_description }}&via=bwelectron" target="_blank"><i class="fa fa-twitter"></i> tweet</a>
    </span>
  </h1>

  <div class="details">Submitted by <a href="http://www.github.com/{{ object.author.username }}" target="_blank">{{ object.author.username }}</a> on {{ object.created | date:"M d Y" }}.</div>

  {% if object.description %}
  <p class="lead">{{ object.description|linebreaksbr }}</p>
  {% else %}
  <p class="lead">No further description available.</p>
  {% endif %}

  {% if object.tags %}
  <div class="tags">
  {% for tag in object.tags.all %}
    <a class="tag" href="{% url 'directory:tag-entries' tag.name %}"># {{tag.name}}</a>
  {% endfor %}
  </div>
  {% endif %}

</div>

{% endblock %}

templates/directory/entry-row.html
{% load staticfiles %}

<div class="col-sm-6 col-md-4 entry">

  <div class="entry-cover">
    {% if entry.cover %}
    <a href="{% url 'directory:detail' entry.slug %}"><img class="img-responsive cover" src="{{ entry.cover.url }}" alt="{{ entry.name }}" title="{{ entry.name }}" /></a>
    {% endif %}
  </div>

  <div class="entry-details">
    <h3>
      <a class="title" href="{% url 'directory:detail' entry.slug %}">{{ entry.name }}</a>
      <span class="date">{{ entry.created | date:"M/d" }}</span>
    </h3>

    <p class="lead">{{ entry.short_description }}</p>
    <p class="lead description">{{ entry.description|truncatechars:"125" }}</p>
  </div>

  <div class="entry-footer">
    <div class="tags">
      {% if entry.tags.count %}<span># </span>{% endif %}
      {% for tag in entry.tags.all|slice:":2" %}
        <a class="tag" href="{% url 'directory:tag-entries' tag.name %}">{{tag.name}}</a>{% if not forloop.last %}, {% endif %}
      {% endfor %}
      {% if entry.tags.all.count > 2 %}
      <div class="tag" title="More tags">...</div>
      {% endif %}
    </div>
  </div>

</div>

templates/directory/featured.html
{% load staticfiles %}

{% if featured %}
<div class="container-fluid featured">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        {% if featured.cover %}
        <img src="{{ featured.cover.url }}" alt="{{ featured.name }}" class="img-responsive cover" />
        {% endif %}
      </div>
      <div class="col-md-8 details">

        <h1>
          {{ featured.name }}
          <span class="links">
            <a href="{{ featured.website_url }}" target="_blank"><i class="fa fa-link"></i></a>
            {% if featured.repo_url %}<a href="{{ featured.repo_url }}" target="_blank"><i class="fa fa-github"></i></a>{% endif %}
          </span>
        </h1>

        <p class="lead">{{ featured.short_description }}</p>
        <p class="lead description">{{ featured.description|truncatechars:"250" }}</p>

        {% if featured.tags %}
        <div class="tags">
        {% for tag in featured.tags.all %}
          <a class="tag" href="{% url 'directory:tag-entries' tag.name %}"># {{tag.name}}</a>
        {% endfor %}
        </div>
        {% endif %}

        <a href="{% url 'directory:detail' featured.slug %}" class="btn btn-lg btn-default">Read More</a>

      </div>
    </div>
  </div>
</div>
{% endif %}

templates/directory/search-results.html
{% extends "base.html" %}
{% load entry_row %}
{% block body_class %}search-results{% endblock %}
{% block title %}Search Results - {% endblock %}
{% block pagetitle %}{% if keywords %}Search Results for: {{ keywords }}{% else %}No keywords provided.{% endif %}{% endblock %}

{% block content %}

<div class="container">

  {% if not found %}
    <div class="alert alert-info">We could not find any results. Here are the latest submissions :)</div>
  {% endif %}

  {% if object_list %}
  <div class="latest">
    {% for entry in object_list %}
      {% entry_row entry %}
    {% endfor %}
  </div>
  {% endif %}

</div>

{% endblock %}

templates/directory/stats.html
<div class="container-fluid stats">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-right">
        <h4>Currenty having <span class="count">{{ entries_count }}</span> applications under <span class="count">{{ tags_count }}</span> tags.</h4>
      </div>
    </div>
  </div>
</div>

templates/directory/submit.html
{% extends "base.html" %}
{% block body_class %}submit-page{% endblock %}
{% block title %}Submit - {% endblock %}
{% block pagetitle %}Submit your electron application{% endblock %}

{% block content %}
  <div class="container">
  {% if user.is_authenticated %}
    <div id="submit-form"></div>
  {% else %}
    <h3 class="text-center">Hey! It looks like you have not logged in yet!</h3>
    <a class="btn btn-primary btn-lg btn-theme login-button" href="{{ OAUTH_URL }}"><i class="fa fa-github"></i> Login with GitHub</a>
  {% endif %}
  </div>

{% endblock %}

{% block javascript %}

  {% if user.is_authenticated %}
  <script type="text/javascript">
    $( document ).ready(function() {
      var csrfToken = '{{ csrf_token }}';
      window.setupSubmitForm(csrfToken, '{{ tags|safe }}');
    });
  </script>
  {% endif %}

{% endblock %}

templates/directory/tag-entries.html
{% extends "base.html" %}
{% load entry_row %}

{% block body_class %}submit-page{% endblock %}
{% block title %}Tag: {{ tag_name }} - {% endblock %}
{% block pagetitle %}Entries with the #{{ tag_name }} tag{% endblock %}

{% block content %}

  <div class="container">
    {% for entry in object_list %}
      {% entry_row entry %}
    {% endfor %}

    {% if page_obj.has_previous or page_obj.has_next %}
    <nav>
      <ul class="pager">
        <li class="previous {% if not page_obj.has_previous %}disabled{% endif%}">
          <a href="{% if page_obj.has_previous %}{{ request.path }}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}"><span aria-hidden="true">&larr;</span> Older</a>
        </li>
        <li class="next {% if not page_obj.has_next %}disabled{% endif%}">
          <a href="{% if page_obj.has_next %}{{ request.path }}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}">Newer <span aria-hidden="true">&rarr;</span></a>
        </li>
      </ul>
    </nav>
    {% endif %}

  </div>
{% endblock %}