project/accounts/urls.py
from django.conf.urls import patterns, url
from project.accounts.views import OAuthCallbackView, ProfileView

urlpatterns = patterns('',

    url(r'^oauth-callback/$', OAuthCallbackView.as_view(), name="oauth-callback"),
    url(r'^profile/$', ProfileView.as_view(), name="profile"),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': 'directory:home'}, name='logout'),

)

project/directory/urls.py
from django.conf.urls import patterns, url
from project.directory.views import (
    HomePageView, SubmitEntryView, EntryDetailView,
    TagEntriesListView, SearchResultsView
)

urlpatterns = patterns('',

    url(r'^$', HomePageView.as_view(), name="home"),
    url(r'^submit/$', SubmitEntryView.as_view(), name="submit"),
    url(r'^entries/(?P<slug>[\w-]+)/$', EntryDetailView.as_view(), name='detail'),
    url(r'^tags/(?P<slug>[\w-]+)/$', TagEntriesListView.as_view(), name='tag-entries'),
    url(r'^search/results/$', SearchResultsView.as_view(), name='search-results')
)

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from project.common.views import RobotsView

api_urls = [
    url(r'^directory/', view=include('project.directory.urls_api', namespace='directory')),
]

urlpatterns = [

    url('api/', include(api_urls, namespace='api')),

    url(r'^', view=include('project.directory.urls', namespace='directory')),
    url(r'^accounts/', view=include('project.accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),

    # Robots
    url(regex=r'^robots.txt$', view=RobotsView.as_view()),
]

urlpatterns += staticfiles_urlpatterns()

project/directory/forms.py
from django import forms


class SearchForm(forms.Form):
    keywords = forms.CharField(label='Keywords', max_length=100)

project/common/views.py
from django.conf import settings
from django.views.generic import TemplateView


class RobotsView(TemplateView):

    content_type = 'text/plain'

    def get_template_names(self):

        if settings.DEBUG:
            return "staging-robots.txt"
        else:
            return "production-robots.txt"

templates/common/menu.html
{% load staticfiles %}

<nav class="navbar navbar-default">

  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'directory:home' %}">
        <img class="img-responsive" src="{% static "images/logo-circle-white.png" %}" alt="Built with Electron">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a target="_blank" href="https://www.github.com/manosim/builtwithelectron"><i class="fa fa-github"></i></a></li>
        <li><a target="_blank" href="https://www.twitter.com/bwelectron"><i class="fa fa-twitter"></i></a></li>
      </ul>

      <form class="navbar-form navbar-left" action="{% url 'directory:search-results' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <input type="text" class="form-control" id="id_keywords" maxlength="100" name="keywords" placeholder="Search...">
        </div>
      </form>

      <ul class="nav navbar-nav navbar-right">
        {% if user.is_admin %}<li><a target="_blank" href="{% url 'admin:index' %}">Admin</a></li>{% endif %}
        <li><a href="{% url 'directory:submit' %}">Submit</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'accounts:profile' %}"><img src="{{ user.avatar_url }}" class="avatar" /> {{ user.username }}</a></li>
        <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i> <span class="hidden-sm hidden-md hidden-lg">Logout</span></a></li>
        {% endif %}
        {% if not user.is_authenticated %}
        <li><a href="{{ OAUTH_URL }}"><i class="fa fa-github"></i> Login with GitHub</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>